CREATE TABLE IF NOT EXISTS wallets (
  id         CHAR(36)  PRIMARY KEY,
  user_id    CHAR(36)  NOT NULL,
  balance    BIGINT    NOT NULL DEFAULT 0,
  created_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
